env:
  node: true
  es6: true
  jest: true
extends:
  - 'eslint:recommended'
  - 'plugin:prettier/recommended'
parserOptions:
  sourceType: module
  ecmaVersion: 8
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  prettier/prettier:
    - error:
      singleQuote: true
      trailingComma: es5
